AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: arpem-api

Globals:
  Function:
    Timeout: 5
    Runtime: python3.13
    Architectures: [x86_64]
    Environment:
      Variables:
        INCIDENTS_TABLE: !Ref IncidentsTable
        PYTHONPATH: /var/task/src

Resources:
# ────────────────  API  ────────────────
  ArpemApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: arpem-api
      StageName: Prod
      Auth:
        DefaultAuthorizer: NONE
        AddDefaultAuthorizerToCorsPreflight: false
      Cors:
        AllowOrigin: "'http://localhost:3000'"
        AllowMethods: "'POST,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        MaxAge: "'3600'"

  # ─────────── Create Incident Lambda function ───────────
  CreateIncident:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/incidents_create.handler
      CodeUri: ../../backend
      MemorySize: 256
      Timeout: 15
      Events:
        CreateIncidentApiPost:
          Type: Api
          Properties:
            RestApiId: !Ref ArpemApi
            Path: /incidents_create
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IncidentsTable

  # ─────────── Finalize Incident Lambda function ───────────
  FinalizeIncident:
    Type: AWS::Serverless::Function
    Properties:
      Handler  : src/handlers/incidents_finalize.handler
      CodeUri  : ../../backend
      MemorySize: 256
      Timeout  : 10
      Environment:
        Variables:
          INCIDENTS_TABLE: !Ref IncidentsTable
          HMAC_SECRET    : "super-secret"
      Events:
        VerifyIncidentApi:
          Type: Api
          Properties:
            RestApiId: !Ref ArpemApi
            Path     : /incidents/{id}/verify
            Method   : PATCH
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IncidentsTable

  # ─────────── Generate Upload Link Lambda function ───────────
  GenerateUploadLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/generate_upload_url.handler
      CodeUri: ../../backend
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          EVIDENCE_BUCKET: !Ref EvidenceBucket
      Events:
        GenerateUploadLinkApi:
          Type: Api
          Properties:
            RestApiId: !Ref ArpemApi
            Path: /generate-upload-url
            Method: POST
      Policies:
        - S3WritePolicy:
            BucketName: !Ref EvidenceBucket

  # ─────────── Fetch ALL User Incidents ───────────
  FetchUserIncidents:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/incidents_user.handler
      CodeUri: ../../backend
      MemorySize: 256
      Timeout: 10
      Events:
        GetUserIncidentsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ArpemApi
            Path: /user-incidents
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref IncidentsTable


  # ──────── Data stores etc. ────────
  EvidenceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: arpem-evidence-bucket

  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IncidentsTable
      AttributeDefinitions:
        - AttributeName: incidentId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: incidentId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  CreateIncidentApiUrl:
    Description: "REST API endpoint URL for POST /incidents_create"
    Value: !Sub "${ArpemApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/incidents_create"