AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: arpem-api

Globals:
  Function:
    Timeout: 5
    Runtime: python3.13
    Architectures: [x86_64]
    Environment:
      Variables:
        INCIDENTS_TABLE: !Ref IncidentsTable
        PYTHONPATH: /var/task/src

Resources:
  # ────────────────  API  ────────────────
  ArpemApi:
    Type: AWS::Serverless::Api          # ← v1 (REST) API
    Properties:
      Name: arpem-api
      StageName: Prod
      # If you’re using Cognito/JWT etc. keep your Auth block here
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false   # don’t stick auth on OPTIONS
      Cors:                                  # ← CORS lives here
        AllowOrigin: "'http://localhost:3000'"
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type'"
        MaxAge: "'3600'"            # (optional) cache pre-flight 1 h


  # ─────────── Lambda function ───────────
  CreateIncident:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/incidents_create.handler
      CodeUri: ../../backend
      MemorySize: 256
      Timeout: 15
      Events:
        CreateIncidentApi:
          Type: Api
          Properties:
            RestApiId: !Ref ArpemApi
            Path: /incidents_create
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IncidentsTable

  # ──────── Data stores etc. ────────
  EvidenceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: arpem-evidence-bucket

  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IncidentsTable
      AttributeDefinitions:
        - AttributeName: incidentId
          AttributeType: S
      KeySchema:
        - AttributeName: incidentId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  CreateIncidentApiUrl:
    Description: "HTTP API endpoint URL for POST /incidents_create"
    Value: !Sub "${ArpemApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/incidents_create"