AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  arpem-api

Globals:
  Function:
    Timeout: 5
    Runtime: python3.13
    Architectures:
      - x86_64

Resources:
  GetIncidentStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/get_incident_status/
      Handler: app.lambda_handler
      Events:
        GetIncidentStatusApi:
          Type: Api
          Properties:
            Path: /get-incident-status
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: IncidentsTable
      Environment:
        Variables:
          INCIDENTS_TABLE: IncidentsTable

  SubmitIncidentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/submit_incident/
      Handler: app.lambda_handler
      Events:
        SubmitIncidentApi:
          Type: Api
          Properties:
            Path: /submit-incident
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: IncidentsTable
      Environment:
        Variables:
          INCIDENTS_TABLE: IncidentsTable

  GenerateUploadLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/upload/
      Handler: app.lambda_handler
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /generate-upload-url
            Method: post
      Policies:
        - S3CrudPolicy:
            BucketName: arpem-evidence-bucket
      Environment:
        Variables:
          BUCKET_NAME: arpem-evidence-bucket
      VpcConfig:
        SubnetIds:
          - subnet-0d85d2cf164025957
        SecurityGroupIds:
          - sg-08e0f2a7c4ffb1e0f

  EvidenceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: arpem-evidence-bucket

  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IncidentsTable
      AttributeDefinitions:
        - AttributeName: incidentId
          AttributeType: S
      KeySchema:
        - AttributeName: incidentId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  GenerateUploadLinkApiUrl:
    Description: "API Gateway endpoint URL for /generate-upload-url"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-upload-url"

  GenerateUploadLinkFunctionArn:
    Description: "ARN of the generate upload Lambda function"
    Value: !GetAtt GenerateUploadLinkFunction.Arn

  SubmitIncidentApiUrl:
    Description: "API Gateway endpoint URL for /submit-incident"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submit-incident"

  GetIncidentStatusApiUrl:
    Description: "API Gateway endpoint URL for /get-incident-status"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-incident-status"
